In [1]:
import sys
print(sys.executable)

c:\Users\EAG28\OneDrive\Документы\2026W\Project\ev-traffic-charging-prediction\.venv\Scripts\python.exe

In [85]:
import pandas as pd

In [87]:
RANDOM_STATE = 42

In [3]:
nodes = pd.read_csv("../data/raw/shenzhen/node_shenzhen.csv")
edges = pd.read_csv("../data/raw/shenzhen/edge_shenzhen.csv")

trajectories = pd.read_csv("../data/raw/shenzhen/traj_shenzhen_20201104.csv")

In [4]:
display(nodes.head())
display(edges.head())
display(trajectories.head())

print("Nodes:", nodes.shape)
print("Edges:", edges.shape)
print("Trajectories:", trajectories.shape)

   NodeID   Longitude   Latitude  HasCamera
0       0  114.049332  22.690314          0
1       1  114.048449  22.675017          0
2       2  114.046650  22.685071          0
3       3  114.048557  22.676590          0
4       4  114.050360  22.681492          0

,Origin,Destination,Class,Geometry,Length
0,0,1,motorway,114.049332-22.690314_114.048995-22.688018_114....,1699.3
1,0,2,motorway_link,114.049332-22.690314_114.049234-22.689926_114....,663.9
2,1,10107,motorway,114.048449-22.675017_114.048508-22.673645,152.0
3,2,8,motorway_link,114.04665-22.685071_114.046193-22.684735_114.0...,366.4
4,2,7,motorway_link,114.04665-22.685071_114.046416-22.684763_114.0...,1202.3

,VehicleID,TripID,Points,DepartureTime,Duration,Length
0,0,0,1226-41543.0_11706-41546.2_1227-41552.5_10226-...,41543.0,1165.0,6764.6
1,0,1,11699-62360.0_1495-62374.7_10227-62571.3_10225...,62360.0,419.0,2455.3
2,1,0,11699-32737.0_1495-32742.6_10227-32805.0_10225...,32737.0,5680.0,19380.9
3,1,1,3829-60593.0_8182-60624.4_8181-60633.1_3838-60...,60593.0,1921.5,5086.3
4,1,2,11699-64357.5_1495-64371.4_10227-64556.9_10225...,64357.5,545.5,2455.3

Nodes: (11933, 4)
Edges: (27410, 5)
Trajectories: (569057, 6)

Exploring one trajectory

In [5]:
points = trajectories.iloc[0]["Points"]

print(points)

1226-41543.0_11706-41546.2_1227-41552.5_10226-41560.1_11320-41574.3_11699-41608.0_1188-41620.6_1190-41640.4_4209-41667.0_1246-41784.9_1255-41929.7_1254-41984.6_10261-42006.0_1253-42031.0_1256-42136.2_1258-42178.4_8954-42216.7_8958-42294.9_4544-42459.3_4547-42504.1_4550-42539.1_11775-42554.4_6851-42561.9_9204-42625.5_6851-42700.6_11775-42708.0

In [6]:
# parsing the trajectory
parsed_points = [
    (int(point.split("-")[0]), float(point.split("-")[1]))
    for point in points.split("_")
]

parsed_points

[(1226, 41543.0),
 (11706, 41546.2),
 (1227, 41552.5),
 (10226, 41560.1),
 (11320, 41574.3),
 (11699, 41608.0),
 (1188, 41620.6),
 (1190, 41640.4),
 (4209, 41667.0),
 (1246, 41784.9),
 (1255, 41929.7),
 (1254, 41984.6),
 (10261, 42006.0),
 (1253, 42031.0),
 (1256, 42136.2),
 (1258, 42178.4),
 (8954, 42216.7),
 (8958, 42294.9),
 (4544, 42459.3),
 (4547, 42504.1),
 (4550, 42539.1),
 (11775, 42554.4),
 (6851, 42561.9),
 (9204, 42625.5),
 (6851, 42700.6),
 (11775, 42708.0)]

In [7]:
print("Number of points:", len(parsed_points))
print("First 10 points:")
parsed_points[:10]

Number of points: 26
First 10 points:

[(1226, 41543.0),
 (11706, 41546.2),
 (1227, 41552.5),
 (10226, 41560.1),
 (11320, 41574.3),
 (11699, 41608.0),
 (1188, 41620.6),
 (1190, 41640.4),
 (4209, 41667.0),
 (1246, 41784.9)]

In [8]:
node_pairs = [
    (parsed_points[i][0], parsed_points[i + 1][0])
    for i in range(len(parsed_points) - 1)
]

node_pairs[:10]

[(1226, 11706),
 (11706, 1227),
 (1227, 10226),
 (10226, 11320),
 (11320, 11699),
 (11699, 1188),
 (1188, 1190),
 (1190, 4209),
 (4209, 1246),
 (1246, 1255)]

Veryfying whether these are real node edges

In [9]:
edge_pairs = set(zip(edges["Origin"], edges["Destination"]))

edge_check = [
    (origin, destination, (origin, destination) in edge_pairs)
    for origin, destination in node_pairs
]

edge_check[:10]

[(1226, 11706, True),
 (11706, 1227, True),
 (1227, 10226, True),
 (10226, 11320, True),
 (11320, 11699, True),
 (11699, 1188, True),
 (1188, 1190, True),
 (1190, 4209, True),
 (4209, 1246, True),
 (1246, 1255, True)]

In [10]:
all_edges_valid = all(is_valid for _, _, is_valid in edge_check)

print("All consecutive nodes are valid edges:", all_edges_valid)
print("Valid edges:", sum(is_valid for _, _, is_valid in edge_check))
print("Total transitions:", len(edge_check))

All consecutive nodes are valid edges: True
Valid edges: 25
Total transitions: 25

Visualising the trajectory via folium package

In [11]:
import folium

# Fast lookup: NodeID -> (latitude, longitude)
node_coordinates = nodes.set_index("NodeID")[["Latitude", "Longitude"]]

# Convert our trajectory node IDs into map coordinates
route_coordinates = [
    [
        node_coordinates.loc[node_id, "Latitude"],
        node_coordinates.loc[node_id, "Longitude"],
    ]
    for node_id, _ in parsed_points
]

route_coordinates[:5]

[[np.float64(22.634135), np.float64(114.032018)],
 [np.float64(22.634049), np.float64(114.032194)],
 [np.float64(22.634021), np.float64(114.032614)],
 [np.float64(22.633586), np.float64(114.033572)],
 [np.float64(22.633286), np.float64(114.036184)]]

In [12]:
route_map = folium.Map(
    location=route_coordinates[0],
    zoom_start=13,
    tiles=None,
)

folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Esri World Street Map",
).add_to(route_map)

folium.PolyLine(
    route_coordinates,
    weight=5,
).add_to(route_map)

folium.Marker(
    route_coordinates[0],
    tooltip="Start",
).add_to(route_map)

folium.Marker(
    route_coordinates[-1],
    tooltip="End",
).add_to(route_map)

route_map.save("../route_map.html")

Trying to follow road geometry

In [13]:
print(edges.iloc[0]["Geometry"])

114.049332-22.690314_114.048995-22.688018_114.048866-22.687063_114.048738-22.685958_114.048635-22.685032_114.048537-22.683722_114.048481-22.68278_114.048395-22.681357_114.048369-22.680485_114.048377-22.678973_114.048394-22.677271_114.048449-22.675017

In [14]:
edge_geometries = {
    (row.Origin, row.Destination): row.Geometry
    for row in edges.itertuples()
}

In [15]:
edge_geometries[(1226, 11706)]

'114.032018-22.634135_114.032201-22.634134_114.032194-22.634049'

In [16]:
def parse_geometry(geometry):
    return [
        [float(point.split("-")[1]), float(point.split("-")[0])]
        for point in geometry.split("_")
    ]

In [17]:
parse_geometry(edge_geometries[(1226, 11706)])[:5]

[[22.634135, 114.032018], [22.634134, 114.032201], [22.634049, 114.032194]]

In [18]:
# create a new map

road_map = folium.Map(
    location=route_coordinates[0],
    zoom_start=13,
    tiles=None,
)

folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Esri World Street Map",
).add_to(road_map)

In [19]:
# draw an actual edge

for origin, destination in node_pairs:
    geometry = edge_geometries[(origin, destination)]

    folium.PolyLine(
        parse_geometry(geometry),
        weight=5,
    ).add_to(road_map)

In [20]:
# adding start and end
folium.Marker(
    route_coordinates[0],
    tooltip="Start",
).add_to(road_map)

folium.Marker(
    route_coordinates[-1],
    tooltip="End",
).add_to(road_map)

road_map.save("../road_geometry_map.html")

Extracting intersection movements for one trajection

In [21]:
movements = []

for i in range(1, len(parsed_points) - 1):
    incoming_node = parsed_points[i - 1][0]
    intersection = parsed_points[i][0]
    outgoing_node = parsed_points[i + 1][0]
    time = parsed_points[i][1]

    movements.append(
        {
            "IncomingNode": incoming_node,
            "Intersection": intersection,
            "OutgoingNode": outgoing_node,
            "Time": time,
        }
    )

In [22]:
movements_df = pd.DataFrame(movements)

movements_df.head(10)

   IncomingNode  Intersection  OutgoingNode     Time
0          1226         11706          1227  41546.2
1         11706          1227         10226  41552.5
2          1227         10226         11320  41560.1
3         10226         11320         11699  41574.3
4         11320         11699          1188  41608.0
5         11699          1188          1190  41620.6
6          1188          1190          4209  41640.4
7          1190          4209          1246  41667.0
8          4209          1246          1255  41784.9
9          1246          1255          1254  41929.7

In [23]:
# time format change

movements_df["TimeOfDay"] = (
    pd.to_datetime(movements_df["Time"], unit="s")
    .dt.strftime("%H:%M:%S")
)

movements_df["Hour"] = (movements_df["Time"] // 3600).astype(int)

movements_df.head(10)

   IncomingNode  Intersection  OutgoingNode     Time TimeOfDay  Hour
0          1226         11706          1227  41546.2  11:32:26    11
1         11706          1227         10226  41552.5  11:32:32    11
2          1227         10226         11320  41560.1  11:32:40    11
3         10226         11320         11699  41574.3  11:32:54    11
4         11320         11699          1188  41608.0  11:33:28    11
5         11699          1188          1190  41620.6  11:33:40    11
6          1188          1190          4209  41640.4  11:34:00    11
7          1190          4209          1246  41667.0  11:34:27    11
8          4209          1246          1255  41784.9  11:36:24    11
9          1246          1255          1254  41929.7  11:38:49    11

Testing the trajectories parcer

In [24]:
from ev_traffic.trajectories import extract_movements, parse_trajectory

test_points = trajectories.iloc[0]["Points"]

parsed = parse_trajectory(test_points)
movements = extract_movements(parsed)

len(parsed), len(movements)

(26, 24)

In [25]:
movements[:5]

[(1226, 11706, 1227, 41546.2),
 (11706, 1227, 10226, 41552.5),
 (1227, 10226, 11320, 41560.1),
 (10226, 11320, 11699, 41574.3),
 (11320, 11699, 1188, 41608.0)]

Extracting movements from multiple trajectories

In [26]:
movement_records = []

for row in trajectories.head(1000).itertuples(index=False):
    parsed = parse_trajectory(row.Points)
    trip_movements = extract_movements(parsed)

    for incoming, intersection, outgoing, time in trip_movements:
        movement_records.append(
            {
                "VehicleID": row.VehicleID,
                "TripID": row.TripID,
                "IncomingNode": incoming,
                "Intersection": intersection,
                "OutgoingNode": outgoing,
                "Time": time,
            }
        )

movements_sample = pd.DataFrame(movement_records)

movements_sample.head()

   VehicleID  TripID  IncomingNode  Intersection  OutgoingNode     Time
0          0       0          1226         11706          1227  41546.2
1          0       0         11706          1227         10226  41552.5
2          0       0          1227         10226         11320  41560.1
3          0       0         10226         11320         11699  41574.3
4          0       0         11320         11699          1188  41608.0

In [27]:
movements_sample.shape

(28607, 6)

In [28]:
movements_sample[["VehicleID", "TripID"]].drop_duplicates().shape

(972, 2)

In [29]:
movements_sample.isna().sum()

VehicleID       0
TripID          0
IncomingNode    0
Intersection    0
OutgoingNode    0
Time            0
dtype: int64

In [30]:
# searching for missing trajectories

point_counts = (
    trajectories.head(1000)["Points"]
    .str.count("_")
    .add(1)
)

point_counts.value_counts().sort_index().head(10)

Points
2     26
3     41
4     29
5     52
6     36
7     37
8     27
9     27
10    31
11    28
Name: count, dtype: int64

In [31]:
(point_counts < 3).sum()

np.int64(26)

1000 input trajectories:
- 974 trajectories with ≥3 nodes → can define at least one A → B → C movement
- 26 trajectories with only 2 nodes → no intersection movement possible

Validation  of road connections

In [32]:
# set of all directed road connections
edge_pairs = set(zip(edges["Origin"], edges["Destination"], strict=True))

len(edge_pairs), len(edges)

(27410, 27410)

In [33]:
incoming_edges_valid = [
    (incoming, intersection) in edge_pairs
    for incoming, intersection in zip(
        movements_sample["IncomingNode"],
        movements_sample["Intersection"],
        strict=True,
    )
]

outgoing_edges_valid = [
    (intersection, outgoing) in edge_pairs
    for intersection, outgoing in zip(
        movements_sample["Intersection"],
        movements_sample["OutgoingNode"],
        strict=True,
    )
]

sum(incoming_edges_valid), sum(outgoing_edges_valid), len(movements_sample)

(28607, 28607, 28607)

In [34]:
# test on missing nodes
invalid_incoming = movements_sample[
    ~pd.Series(incoming_edges_valid, index=movements_sample.index)
]

invalid_outgoing = movements_sample[
    ~pd.Series(outgoing_edges_valid, index=movements_sample.index)
]

invalid_incoming.head(10)

Empty DataFrame
Columns: [VehicleID, TripID, IncomingNode, Intersection, OutgoingNode, Time]
Index: []

In [35]:
invalid_outgoing.head(10)

Empty DataFrame
Columns: [VehicleID, TripID, IncomingNode, Intersection, OutgoingNode, Time]
Index: []

Found duplicate nodes

In [36]:
duplicate_node_movements = movements_sample[
    (movements_sample["IncomingNode"] == movements_sample["Intersection"])
    | (movements_sample["Intersection"] == movements_sample["OutgoingNode"])
]

duplicate_node_movements.shape

(0, 6)

In [37]:
duplicate_node_movements.head(10)

Empty DataFrame
Columns: [VehicleID, TripID, IncomingNode, Intersection, OutgoingNode, Time]
Index: []

In [38]:
invalid_incoming_non_duplicate = invalid_incoming[
    invalid_incoming["IncomingNode"] != invalid_incoming["Intersection"]
]

invalid_outgoing_non_duplicate = invalid_outgoing[
    invalid_outgoing["Intersection"] != invalid_outgoing["OutgoingNode"]
]

len(invalid_incoming_non_duplicate), len(invalid_outgoing_non_duplicate)

(0, 0)

Theory proved correct and the nodes are indeed duplicates and there needs to be a correction on fake movements. Needs to be an exclusion of duplicate nodes. Corrections to trajectories.py. Will remove only consecutive duplicates, since if car genuinly travels in circles it's not a duplicate.

Done - 0 duplicates.

## Road classes and highway exits

Inspecting the road classes and network structure to understand how intersections
and highway exits can be distinguished

In [39]:
edges["Class"].value_counts(dropna=False)

Class
residential       7597
tertiary          6166
secondary         3779
primary           3535
unclassified      3348
primary_link       924
trunk              471
motorway_link      414
trunk_link         379
secondary_link     279
motorway           224
living_street      209
tertiary_link       85
Name: count, dtype: int64

In [40]:
highway_classes = ["motorway", "motorway_link", "trunk", "trunk_link"]

edges[edges["Class"].isin(highway_classes)]["Class"].value_counts()

Class
trunk            471
motorway_link    414
trunk_link       379
motorway         224
Name: count, dtype: int64

In [41]:
highway_edges = edges[edges["Class"].isin(highway_classes)].copy()

highway_edges.head(10)

,Origin,Destination,Class,Geometry,Length
0,0,1,motorway,114.049332-22.690314_114.048995-22.688018_114....,1699.3
1,0,2,motorway_link,114.049332-22.690314_114.049234-22.689926_114....,663.9
2,1,10107,motorway,114.048449-22.675017_114.048508-22.673645,152.0
3,2,8,motorway_link,114.04665-22.685071_114.046193-22.684735_114.0...,366.4
4,2,7,motorway_link,114.04665-22.685071_114.046416-22.684763_114.0...,1202.3
5,3,4,motorway_link,114.048557-22.67659_114.04858-22.677141_114.04...,600.3
6,3,5,motorway,114.048557-22.67659_114.04854-22.677263_114.04...,1733.7
7,4,6,motorway_link,114.05036-22.681492_114.050678-22.681798_114.0...,1133.1
8,4,7,motorway_link,114.05036-22.681492_114.050815-22.681816_114.0...,348.8
9,5,11895,motorway,114.049885-22.692168_114.049963-22.692642_114....,76.0

It seems like at node 0, a vehicle may have a choice between going forward or entering a motorway-link edge. Looks like an exit/divergence point

In [42]:
candidate_nodes = [0, 2, 3, 4]

edges[edges["Origin"].isin(candidate_nodes)].sort_values(
    ["Origin", "Class", "Destination"]
)[["Origin", "Destination", "Class", "Length"]]

   Origin  Destination          Class  Length
0       0            1       motorway  1699.3
1       0            2  motorway_link   663.9
4       2            7  motorway_link  1202.3
3       2            8  motorway_link   366.4
6       3            5       motorway  1733.7
5       3            4  motorway_link   600.3
7       4            6  motorway_link  1133.1
8       4            7  motorway_link   348.8

origins 0 and 3 seem to be candidates for highway divergence points (lead both forward along motorway and motorway links)
next: what road did the vehicle arrive on?

In [43]:
candidate_nodes = [0, 3]

for node in candidate_nodes:
    print(f"\nNode {node}")

    print("Incoming:")
    display(
        edges[edges["Destination"] == node][
            ["Origin", "Destination", "Class", "Length"]
        ]
    )

    print("Outgoing:")
    display(
        edges[edges["Origin"] == node][
            ["Origin", "Destination", "Class", "Length"]
        ]
    )

Node 0
Incoming:

       Origin  Destination     Class  Length
27373   11914            0  motorway   807.3

Outgoing:

   Origin  Destination          Class  Length
0       0            1       motorway  1699.3
1       0            2  motorway_link   663.9

Node 3
Incoming:

      Origin  Destination     Class  Length
2156    1093            3  motorway   313.0

Outgoing:

   Origin  Destination          Class  Length
5       3            4  motorway_link   600.3
6       3            5       motorway  1733.7

In [44]:
# finsing all candidates for the highway decision points
motorway_exit_candidates = []

for node in edges["Origin"].unique():
    incoming_classes = set(
        edges.loc[edges["Destination"] == node, "Class"]
    )
    outgoing_classes = set(
        edges.loc[edges["Origin"] == node, "Class"]
    )

    if (
        "motorway" in incoming_classes
        and "motorway" in outgoing_classes
        and "motorway_link" in outgoing_classes
    ):
        motorway_exit_candidates.append(node)

print("Number of motorway exit candidates:", len(motorway_exit_candidates))

Number of motorway exit candidates: 80

In [45]:
sample_candidates = motorway_exit_candidates[::10]

for node in sample_candidates:
    incoming = edges[edges["Destination"] == node]
    outgoing = edges[edges["Origin"] == node]

    print(f"\nNode {node}")
    print(
        "Incoming:",
        list(zip(incoming["Class"], incoming["Origin"])),
    )
    print(
        "Outgoing:",
        list(zip(outgoing["Class"], outgoing["Destination"])),
    )

Node 0
Incoming: [('motorway', 11914)]
Outgoing: [('motorway', 1), ('motorway_link', 2)]

Node 487
Incoming: [('motorway', 9994)]
Outgoing: [('motorway_link', 11916), ('motorway', 11917)]

Node 1094
Incoming: [('motorway', 8885)]
Outgoing: [('motorway_link', 75), ('motorway', 1095)]

Node 3049
Incoming: [('motorway', 11828)]
Outgoing: [('motorway', 3050), ('motorway_link', 3051)]

Node 3434
Incoming: [('motorway', 10297)]
Outgoing: [('motorway', 3435), ('motorway_link', 3436)]

Node 3696
Incoming: [('motorway', 9528)]
Outgoing: [('motorway_link', 3034), ('motorway', 3037)]

Node 6399
Incoming: [('motorway', 6398)]
Outgoing: [('motorway_link', 6409), ('motorway', 6410)]

Node 7952
Incoming: [('motorway', 3263)]
Outgoing: [('motorway_link', 7949), ('motorway', 7953)]

are trunk roads also highways or only motorways?

In [46]:
trunk_exit_candidates = []

for node in edges["Origin"].unique():
    incoming_classes = set(
        edges.loc[edges["Destination"] == node, "Class"]
    )
    outgoing_classes = set(
        edges.loc[edges["Origin"] == node, "Class"]
    )

    if (
        "trunk" in incoming_classes
        and "trunk" in outgoing_classes
        and "trunk_link" in outgoing_classes
    ):
        trunk_exit_candidates.append(node)

print("Number of trunk exit candidates:", len(trunk_exit_candidates))
print("First 20:", trunk_exit_candidates[:20])

Number of trunk exit candidates: 116
First 20: [np.int64(17), np.int64(33), np.int64(50), np.int64(53), np.int64(56), np.int64(71), np.int64(93), np.int64(96), np.int64(100), np.int64(129), np.int64(162), np.int64(197), np.int64(323), np.int64(360), np.int64(361), np.int64(364), np.int64(431), np.int64(437), np.int64(440), np.int64(456)]

In [47]:
sample_trunk_candidates = trunk_exit_candidates[::15]

for node in sample_trunk_candidates:
    incoming = edges[edges["Destination"] == node]
    outgoing = edges[edges["Origin"] == node]

    print(f"\nNode {node}")
    print(
        "Incoming:",
        list(zip(incoming["Class"], incoming["Origin"])),
    )
    print(
        "Outgoing:",
        list(zip(outgoing["Class"], outgoing["Destination"])),
    )

Node 17
Incoming: [('trunk', 16)]
Outgoing: [('trunk_link', 18), ('trunk', 11760)]

Node 364
Incoming: [('trunk', 8272)]
Outgoing: [('trunk_link', 365), ('trunk', 366)]

Node 789
Incoming: [('trunk', 7021)]
Outgoing: [('trunk_link', 790), ('trunk', 791)]

Node 921
Incoming: [('trunk', 917)]
Outgoing: [('trunk', 6078), ('trunk_link', 919)]

Node 1106
Incoming: [('trunk', 1111), ('residential', 3684), ('primary', 3685)]
Outgoing: [('trunk_link', 3683), ('trunk', 1071), ('residential', 3684)]

Node 3033
Incoming: [('trunk', 3032)]
Outgoing: [('trunk', 4375), ('trunk_link', 4377)]

Node 4338
Incoming: [('trunk', 2635)]
Outgoing: [('trunk', 8270), ('trunk_link', 11662)]

Node 8276
Incoming: [('trunk', 3828)]
Outgoing: [('trunk_link', 8275), ('trunk', 11662)]

##### Potential Highway logic:

incoming Class = trunk/motorway -> decision node ->

outgoing same main-road class → CONTINUE **OR** outgoing corresponding *_link → EXIT

### Enrich movements with road classes

Adding the road class of the incoming and outgoing edges to each extracted movement.
This allows intersection movements and highway exit/continue behavior to be
analyzed separately

In [48]:
print(type(movements))
print(type(movements_df) if "movements_df" in globals() else "movements_df does not exist")

<class 'list'>
<class 'pandas.DataFrame'>

In [49]:
edge_classes = edges[["Origin", "Destination", "Class"]]

movements_enriched = (
    movements_df
    .merge(
        edge_classes,
        left_on=["IncomingNode", "Intersection"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "IncomingClass"})
    .drop(columns=["Origin", "Destination"])
    .merge(
        edge_classes,
        left_on=["Intersection", "OutgoingNode"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "OutgoingClass"})
    .drop(columns=["Origin", "Destination"])
)

movements_enriched.head(10)

,IncomingNode,Intersection,OutgoingNode,Time,TimeOfDay,Hour,IncomingClass,OutgoingClass
0,1226,11706,1227,41546.2,11:32:26,11,primary,primary
1,11706,1227,10226,41552.5,11:32:32,11,primary,primary
2,1227,10226,11320,41560.1,11:32:40,11,primary,primary
3,10226,11320,11699,41574.3,11:32:54,11,primary,primary
4,11320,11699,1188,41608.0,11:33:28,11,primary,primary
5,11699,1188,1190,41620.6,11:33:40,11,primary,primary
6,1188,1190,4209,41640.4,11:34:00,11,primary,primary
7,1190,4209,1246,41667.0,11:34:27,11,primary,secondary
8,4209,1246,1255,41784.9,11:36:24,11,secondary,secondary
9,1246,1255,1254,41929.7,11:38:49,11,secondary,secondary

In [50]:
movements_enriched[["IncomingClass", "OutgoingClass"]].isna().sum()

IncomingClass    0
OutgoingClass    0
dtype: int64

## Highway exit behavior

Classify movements arriving on a motorway or trunk road according to whether
the vehicle continues on the same road class or takes the corresponding link
road. Link movements are treated as candidate highway exits.

In [51]:
def classify_highway_movement(row):
    if row["IncomingClass"] == "motorway":
        if row["OutgoingClass"] == "motorway":
            return "continue"
        if row["OutgoingClass"] == "motorway_link":
            return "exit"

    if row["IncomingClass"] == "trunk":
        if row["OutgoingClass"] == "trunk":
            return "continue"
        if row["OutgoingClass"] == "trunk_link":
            return "exit"

    return None


movements_enriched["HighwayMovement"] = movements_enriched.apply(
    classify_highway_movement,
    axis=1,
)

movements_enriched["HighwayMovement"].value_counts(dropna=False)

HighwayMovement
None    24
Name: count, dtype: int64

In [52]:
[(name, value.shape) for name, value in globals().items()
 if isinstance(value, pd.DataFrame) and "IncomingNode" in value.columns]

[('___', (10, 8)),
 ('movements_df', (24, 6)),
 ('_22', (10, 4)),
 ('_23', (10, 6)),
 ('movements_sample', (28607, 6)),
 ('_26', (5, 6)),
 ('invalid_incoming', (0, 6)),
 ('invalid_outgoing', (0, 6)),
 ('_34', (0, 6)),
 ('_35', (0, 6)),
 ('duplicate_node_movements', (0, 6)),
 ('_37', (0, 6)),
 ('invalid_incoming_non_duplicate', (0, 6)),
 ('invalid_outgoing_non_duplicate', (0, 6)),
 ('movements_enriched', (24, 9)),
 ('_49', (10, 8))]

In [53]:
movements_enriched = (
    movements_sample
    .merge(
        edge_classes,
        left_on=["IncomingNode", "Intersection"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "IncomingClass"})
    .drop(columns=["Origin", "Destination"])
    .merge(
        edge_classes,
        left_on=["Intersection", "OutgoingNode"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "OutgoingClass"})
    .drop(columns=["Origin", "Destination"])
)

movements_enriched.shape

(28607, 8)

In [54]:
movements_enriched["HighwayMovement"] = movements_enriched.apply(
    classify_highway_movement,
    axis=1,
)

movements_enriched["HighwayMovement"].value_counts(dropna=False)

HighwayMovement
NaN         28306
continue      270
exit           31
Name: count, dtype: int64

In [55]:
movements_enriched[
    movements_enriched["HighwayMovement"] == "exit"
].head(15)

,VehicleID,TripID,IncomingNode,Intersection,OutgoingNode,Time,IncomingClass,OutgoingClass,HighwayMovement
151,2,0,11775,1093,9204,51768.7,motorway,motorway_link,exit
847,15,0,11775,1093,9204,63250.6,motorway,motorway_link,exit
1905,36,1,1102,1103,1096,60214.5,trunk,trunk_link,exit
1918,36,1,11775,1093,9204,60844.7,motorway,motorway_link,exit
2693,50,1,1102,1103,1096,49094.3,trunk,trunk_link,exit
2697,50,1,1097,1098,938,49279.3,motorway,motorway_link,exit
2701,50,2,11620,1097,3294,61765.4,trunk,trunk_link,exit
2710,51,0,11620,1097,3294,52812.4,trunk,trunk_link,exit
2998,56,1,11620,1097,3294,35265.2,trunk,trunk_link,exit
3090,56,3,11620,1097,3294,50796.5,trunk,trunk_link,exit
3178,56,3,11775,1093,9204,55025.4,motorway,motorway_link,exit
6533,116,3,1102,1103,1096,55827.5,trunk,trunk_link,exit
6563,120,0,11620,1097,3294,49327.8,trunk,trunk_link,exit
7695,127,0,11620,1097,3294,32456.1,trunk,trunk_link,exit
10618,162,0,11620,1097,3294,44802.0,trunk,trunk_link,exit

In [56]:
highway_movements = movements_enriched[
    movements_enriched["HighwayMovement"].notna()
].copy()

candidate_nodes = set(motorway_exit_candidates) | set(trunk_exit_candidates)

highway_movements["IsExitDecisionPoint"] = (
    highway_movements["Intersection"].isin(candidate_nodes)
)

highway_movements["IsExitDecisionPoint"].value_counts()

IsExitDecisionPoint
False    269
True      32
Name: count, dtype: int64

More decision poimts than initially identified, needs investigation

In [57]:
exit_decision_movements = highway_movements[
    highway_movements["IsExitDecisionPoint"]
].copy()

exit_decision_movements["HighwayMovement"].value_counts()

HighwayMovement
exit        17
continue    15
Name: count, dtype: int64

In [58]:
exit_decision_movements.groupby(
    ["Intersection", "IncomingClass", "HighwayMovement"]
).size().unstack(fill_value=0).sort_values(
    "exit",
    ascending=False,
)

HighwayMovement             continue  exit
Intersection IncomingClass
1093         motorway              0     8
1103         trunk                 0     6
74           motorway              5     2
1098         motorway              4     1
360          trunk                 1     0
1090         motorway              5     0

## Test network.py

In [59]:
from ev_traffic.network import find_highway_exit_candidates

highway_exit_candidates = find_highway_exit_candidates(edges)

print("Highway exit candidates:", len(highway_exit_candidates))

Highway exit candidates: 196

In [60]:
manual_candidates = set(motorway_exit_candidates) | set(trunk_exit_candidates)

print("Missing from function:", manual_candidates - highway_exit_candidates)
print("Extra from function:", highway_exit_candidates - manual_candidates)

Missing from function: set()
Extra from function: set()

In [61]:
import importlib
import ev_traffic.network
importlib.reload(ev_traffic.network)
from ev_traffic.network import classify_highway_movement

movements_enriched["HighwayMovementNew"] = movements_enriched.apply(
    lambda row: classify_highway_movement(
        incoming_class=row["IncomingClass"],
        outgoing_class=row["OutgoingClass"],
        intersection=int(row["Intersection"]),
        exit_candidates=highway_exit_candidates,
    ),
    axis=1,
)

movements_enriched["HighwayMovementNew"].value_counts(dropna=False)

HighwayMovementNew
NaN         28575
exit           17
continue       15
Name: count, dtype: int64

In [62]:
print("movements_sample:", movements_sample.shape)
print("movements_enriched:", movements_enriched.shape)

movements_sample: (28607, 6)
movements_enriched: (28607, 10)

In [63]:
movements_enriched = (
    movements_sample
    .merge(
        edge_classes,
        left_on=["IncomingNode", "Intersection"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "IncomingClass"})
    .drop(columns=["Origin", "Destination"])
    .merge(
        edge_classes,
        left_on=["Intersection", "OutgoingNode"],
        right_on=["Origin", "Destination"],
        how="left",
    )
    .rename(columns={"Class": "OutgoingClass"})
    .drop(columns=["Origin", "Destination"])
)

print(movements_enriched.shape)

(28607, 8)

In [64]:
movements_enriched["HighwayMovement"] = movements_enriched.apply(
    lambda row: classify_highway_movement(
        incoming_class=row["IncomingClass"],
        outgoing_class=row["OutgoingClass"],
        intersection=int(row["Intersection"]),
        exit_candidates=highway_exit_candidates,
    ),
    axis=1,
)

movements_enriched["HighwayMovement"].value_counts(dropna=False)

HighwayMovement
NaN         28575
exit           17
continue       15
Name: count, dtype: int64

08.10.2026 checking the data that exists before trying to process bigger batches

In [66]:
print("Number of trajectories:", len(trajectories))
print("Shape:", trajectories.shape)
print("Columns:", trajectories.columns.tolist())

display(trajectories.head(3))

Number of trajectories: 569057
Shape: (569057, 6)
Columns: ['VehicleID', 'TripID', 'Points', 'DepartureTime', 'Duration', 'Length']

,VehicleID,TripID,Points,DepartureTime,Duration,Length
0,0,0,1226-41543.0_11706-41546.2_1227-41552.5_10226-...,41543.0,1165.0,6764.6
1,0,1,11699-62360.0_1495-62374.7_10227-62571.3_10225...,62360.0,419.0,2455.3
2,1,0,11699-32737.0_1495-32742.6_10227-32805.0_10225...,32737.0,5680.0,19380.9

In [ ]:
# num of recorded points per trajectory
point_counts = trajectories["Points"].str.count("_") + 1

print(point_counts.describe())
print("Total recorded points:", point_counts.sum())

count    569057.000000
mean         27.413530
std          98.531575
min           2.000000
25%           7.000000
50%          15.000000
75%          30.000000
max       16444.000000
Name: Points, dtype: float64
Total recorded points: 15599861

Check existing extraction function

In [68]:
import inspect

print(inspect.signature(parse_trajectory))
print(inspect.signature(extract_movements))

(points: str) -> list[tuple[int, float]]
(trajectory: list[tuple[int, float]]) -> list[tuple[int, int, int, float]]

Testing extraction on 10k trajectories

In [69]:
from time import perf_counter

sample = trajectories.head(10_000)

start = perf_counter()
total_movements = 0

for points in sample["Points"]:
    parsed = parse_trajectory(points)
    movements = extract_movements(parsed)
    total_movements += len(movements)

elapsed = perf_counter() - start

print(f"Trajectories processed: {len(sample):,}")
print(f"Movements extracted: {total_movements:,}")
print(f"Processing time: {elapsed:.2f} seconds")

Trajectories processed: 10,000
Movements extracted: 296,550
Processing time: 0.33 seconds

Process full dataset

In [70]:
from time import perf_counter

start = perf_counter()

records = []

for vehicle_id, trip_id, points in trajectories[
    ["VehicleID", "TripID", "Points"]
].itertuples(index=False, name=None):

    parsed = parse_trajectory(points)

    for incoming, intersection, outgoing, timestamp in extract_movements(parsed):
        records.append((
            vehicle_id,
            trip_id,
            incoming,
            intersection,
            outgoing,
            timestamp,
        ))

movements_df = pd.DataFrame(
    records,
    columns=[
        "VehicleID",
        "TripID",
        "incoming",
        "intersection",
        "outgoing",
        "timestamp",
    ],
)

elapsed = perf_counter() - start

print(f"Movements extracted: {len(movements_df):,}")
print(f"Processing time: {elapsed:.2f} seconds")
print(f"Memory usage: {movements_df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")

display(movements_df.head())

Movements extracted: 14,416,328
Processing time: 38.39 seconds
Memory usage: 659.9 MB

   VehicleID  TripID  incoming  intersection  outgoing  timestamp
0          0       0      1226         11706      1227    41546.2
1          0       0     11706          1227     10226    41552.5
2          0       0      1227         10226     11320    41560.1
3          0       0     10226         11320     11699    41574.3
4          0       0     11320         11699      1188    41608.0

Trying to validate movements against the road network

In [72]:
print([
    name for name in globals()
    if any(term in name.lower() for term in ["edge", "node", "network", "road"])
    and not name.startswith("_")
])

['nodes', 'edges', 'node_pairs', 'edge_pairs', 'edge_check', 'all_edges_valid', 'node_coordinates', 'edge_geometries', 'road_map', 'incoming_node', 'outgoing_node', 'incoming_edges_valid', 'outgoing_edges_valid', 'duplicate_node_movements', 'highway_edges', 'candidate_nodes', 'node', 'edge_classes']

Trying to use edges and edge_pairs to validate movements

In [73]:
print("Type:", type(edge_pairs))
print("Length:", len(edge_pairs))
print("First 5:", list(edge_pairs)[:5])

Type: <class 'set'>
Length: 27410
First 5: [(3014, 3015), (4788, 1584), (266, 268), (7385, 8299), (6388, 6389)]

In [74]:
from time import perf_counter

start = perf_counter()

incoming_valid = [
    (a, b) in edge_pairs
    for a, b in zip(movements_df["incoming"], movements_df["intersection"])
]

outgoing_valid = [
    (b, c) in edge_pairs
    for b, c in zip(movements_df["intersection"], movements_df["outgoing"])
]

movements_df["valid"] = [
    a and b for a, b in zip(incoming_valid, outgoing_valid)
]

print(f"Total movements: {len(movements_df):,}")
print(f"Valid movements: {movements_df['valid'].sum():,}")
print(f"Invalid movements: {(~movements_df['valid']).sum():,}")
print(f"Validity rate: {movements_df['valid'].mean():.2%}")
print(f"Processing time: {perf_counter() - start:.2f} seconds")

Total movements: 14,416,328
Valid movements: 14,416,328
Invalid movements: 0
Validity rate: 100.00%
Processing time: 13.03 seconds

That confirms that all extracted movements are valid against the directed road network

Next need to examine the timestamps

In [75]:
print(movements_df["timestamp"].describe())

print(
    "Minimum hour:",
    movements_df["timestamp"].min() / 3600
)
print(
    "Maximum hour:",
    movements_df["timestamp"].max() / 3600
)

count    1.441633e+07
mean     5.106136e+04
std      1.071358e+04
min      2.880560e+04
25%      4.130300e+04
50%      5.172870e+04
75%      6.043160e+04
max      7.199040e+04
Name: timestamp, dtype: float64
Minimum hour: 8.001555555555555
Maximum hour: 19.99733333333333

Creating hourly time bins

In [76]:
movements_df["hour"] = (
    movements_df["timestamp"] // 3600
).astype("int8")

hourly_counts = (
    movements_df.groupby("hour")
    .size()
    .rename("movements")
)

display(hourly_counts)

hour
8       38851
9     1426186
10    1496915
11    1321937
12    1149724
13    1265173
14    1439016
15    1472303
16    1523729
17    1476246
18    1741930
19      64318
Name: movements, dtype: int64

double checking the boundary hours

In [77]:
movements_df["minute_of_day"] = (
    movements_df["timestamp"] // 60
).astype("int16")

boundary_counts = (
    movements_df.loc[
        movements_df["hour"].isin([8, 19])
    ]
    .groupby(["hour", "minute_of_day"])
    .size()
)

display(boundary_counts)

hour  minute_of_day
8     480               69
      481              125
      482              172
      483              188
      484              194
                      ...
19    1195             348
      1196             358
      1197             320
      1198             246
      1199              70
Length: 120, dtype: int64

hourly coverage of unique trips

In [78]:
trips_per_hour = (
    movements_df.groupby("hour")[["VehicleID", "TripID"]]
    .apply(lambda x: x.drop_duplicates().shape[0])
    .rename("unique_trips")
)

display(trips_per_hour)

hour
8      6604
9     73502
10    77198
11    70303
12    63632
13    68294
14    78437
15    82002
16    84375
17    75181
18    63116
19     7932
Name: unique_trips, dtype: int64

lower movements at 8 am and 7 pm are accompanied by relatively few observed trips
will proceed the initial analysis on data starting 9 am to 6 pm to focus on the "normal" behaving hours

### Calculating conditional turning probabilities

For each incoming road, intersection, and hour, counting how often vehicles choose each outgoing road

In [79]:
model_movements = movements_df.loc[
    movements_df["hour"].between(9, 18)
]

turn_counts = (
    model_movements
    .groupby(
        ["incoming", "intersection", "hour", "outgoing"]
    )
    .size()
    .rename("count")
    .reset_index()
)

turn_counts["total"] = (
    turn_counts
    .groupby(["incoming", "intersection", "hour"])["count"]
    .transform("sum")
)

turn_counts["probability"] = (
    turn_counts["count"] / turn_counts["total"]
)

print("Unique turning combinations:", len(turn_counts))
display(turn_counts.head(10))

Unique turning combinations: 35056

   incoming  intersection  hour  outgoing  count  total  probability
0        74            75     9      1136    152    152          1.0
1        74            75    10      1136    193    193          1.0
2        74            75    11      1136    215    215          1.0
3        74            75    12      1136    227    227          1.0
4        74            75    13      1136    194    194          1.0
5        74            75    14      1136    223    223          1.0
6        74            75    15      1136    179    179          1.0
7        74            75    16      1136    241    241          1.0
8        74            75    17      1136    235    235          1.0
9        74            75    18      1136    100    100          1.0

the probabilies of 10 rows seem weird, need to examine probabilities distribution

In [80]:
print("Total combinations:", len(turn_counts))

print(
    "Probability = 1:",
    (turn_counts["probability"] == 1).sum()
)

print(
    "Probability < 1:",
    (turn_counts["probability"] < 1).sum()
)

display(
    turn_counts.loc[
        turn_counts["probability"] < 1
    ].head(10)
)

Total combinations: 35056
Probability = 1: 11274
Probability < 1: 23782

    incoming  intersection  hour  outgoing  count  total  probability
40       356         11866     9       358    493   2037     0.242023
41       356         11866     9     11861   1544   2037     0.757977
42       356         11866    10       358    368   1742     0.211251
43       356         11866    10     11861   1374   1742     0.788749
44       356         11866    11       358    422   2052     0.205653
45       356         11866    11     11861   1630   2052     0.794347
46       356         11866    12       358    358   1886     0.189820
47       356         11866    12     11861   1528   1886     0.810180
48       356         11866    13       358    394   2465     0.159838
49       356         11866    13     11861   2071   2465     0.840162

Identifying decidion points

In [81]:
decision_points = (
    turn_counts
    .groupby(["incoming", "intersection"])["outgoing"]
    .nunique()
    .rename("n_outgoing")
    .reset_index()
)

print("Total incoming-road/intersection pairs:", len(decision_points))

print(
    "Pairs with multiple observed choices:",
    (decision_points["n_outgoing"] > 1).sum()
)

print(
    "Pairs with only one observed choice:",
    (decision_points["n_outgoing"] == 1).sum()
)

display(decision_points["n_outgoing"].value_counts().sort_index())

Total incoming-road/intersection pairs: 2116
Pairs with multiple observed choices: 975
Pairs with only one observed choice: 1141

n_outgoing
1    1141
2     532
3     236
4     203
5       4
Name: count, dtype: int64

Arounf half of routing decisions are not really decisions since there is only a single observed choice.

Need to measure how much data there is at decision point

In [82]:
branching_pairs = decision_points.loc[
    decision_points["n_outgoing"] > 1,
    ["incoming", "intersection"]
]

branching_movements = model_movements.merge(
    branching_pairs,
    on=["incoming", "intersection"],
    how="inner"
)

print(f"Movements at branching points: {len(branching_movements):,}")
print(f"Share of selected movements: {len(branching_movements) / len(model_movements):.1%}")
print(f"Unique branching pairs: {len(branching_pairs):,}")

Movements at branching points: 8,556,492
Share of selected movements: 59.8%
Unique branching pairs: 975

Create a train/validation/test split - 70/15/15

In [88]:
from sklearn.model_selection import train_test_split

unique_trips = (
    model_movements[["VehicleID", "TripID"]]
    .drop_duplicates()
)

train_trips, remaining_trips = train_test_split(
    unique_trips,
    test_size=0.30,
    random_state=RANDOM_STATE,
)

val_trips, test_trips = train_test_split(
    remaining_trips,
    test_size=0.50,
    random_state=RANDOM_STATE,
)

trip_splits = unique_trips.copy()
trip_splits["split"] = "test"
trip_splits.loc[train_trips.index, "split"] = "train"
trip_splits.loc[val_trips.index, "split"] = "validation"

# Avoid duplicate split columns if rerunning
model_movements = model_movements.drop(
    columns=["split"], errors="ignore"
)

model_movements = model_movements.merge(
    trip_splits,
    on=["VehicleID", "TripID"],
    how="left",
    validate="many_to_one",
)

print("Trips per split:")
print(trip_splits["split"].value_counts())

print("\nMovements per split:")
print(model_movements["split"].value_counts())

Trips per split:
split
train         382671
test           82001
validation     82001
Name: count, dtype: int64

Movements per split:
split
train         10050524
test           2167081
validation     2095554
Name: count, dtype: int64

### Time-independent baseline
learns turning probabilities from the train set only, ignoring hour

In [89]:
train_movements = model_movements.loc[
    model_movements["split"] == "train"
]

baseline_counts = (
    train_movements
    .groupby(["incoming", "intersection", "outgoing"])
    .size()
    .rename("count")
    .reset_index()
)

baseline_counts["total"] = (
    baseline_counts
    .groupby(["incoming", "intersection"])["count"]
    .transform("sum")
)

baseline_counts["probability"] = (
    baseline_counts["count"] / baseline_counts["total"]
)

print("Baseline turning combinations:", len(baseline_counts))
display(baseline_counts.head(10))

Baseline turning combinations: 3731

   incoming  intersection  outgoing  count  total  probability
0        74            75      1136   1336   1336     1.000000
1        74            76      8886   2410   2410     1.000000
2        75          1136      1138   1336   1336     1.000000
3        76          8886      1090   2410   2410     1.000000
4       356         11866       358   2790  13341     0.209130
5       356         11866     11861  10551  13341     0.790870
6       357          6724      6728   5397   5887     0.916766
7       357          6724      6729     28   5887     0.004756
8       357          6724      6730    462   5887     0.078478
9       357         11725      2973    358   2080     0.172115

In [ ]:
# how many of validation movements have transitions that were observed in train set
validation_movements = model_movements.loc[
    model_movements["split"] == "validation"
]

validation_predictions = validation_movements.merge(
    baseline_counts[
        ["incoming", "intersection", "outgoing", "probability"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
)

missing = validation_predictions["probability"].isna()

print(f"Validation movements: {len(validation_predictions):,}")
print(f"Movements without learned probability: {missing.sum():,}")
print(f"Share without learned probability: {missing.mean():.4%}")

Validation movements: 2,095,554
Movements without learned probability: 11
Share without learned probability: 0.0005%

In [92]:
known_approaches = baseline_counts[
    ["incoming", "intersection"]
].drop_duplicates()

unseen_movements = validation_predictions.loc[
    validation_predictions["probability"].isna()
].copy()

unseen_movements = unseen_movements.merge(
    known_approaches.assign(known_approach=True),
    on=["incoming", "intersection"],
    how="left",
)

unseen_movements["known_approach"] = (
    unseen_movements["known_approach"]
    .fillna(False)
    .astype(bool)
)

print(unseen_movements["known_approach"].value_counts())
display(
    unseen_movements[
        ["incoming", "intersection", "outgoing", "hour", "known_approach"]
    ]
)

known_approach
False    7
True     4
Name: count, dtype: int64

    incoming  intersection  outgoing  hour  known_approach
0       6772          6776     11858    15            True
1      11345         11715      1503    14            True
2       1228          1165      1197    13            True
3       1165          1197      1164    13           False
4       1197          1164      1172    13           False
5       1164          1172      1170    13           False
6       1172          1170      1162    13           False
7       1170          1162      1159    13           False
8       1162          1159      1161    13           False
9       1159          1161      1181    13           False
10      1224         11750      9252     9            True

- 4 movements that were observed duting train but the outgoing road wasn't
- 7 movements where the (incoming road, intersection) pair wasn't observed

Preparing the road-network for smoothing

Gonna try Laplace smoothing for the baseline

In [93]:
print(edges.columns.tolist())
display(edges.head(5))

['Origin', 'Destination', 'Class', 'Geometry', 'Length']

,Origin,Destination,Class,Geometry,Length
0,0,1,motorway,114.049332-22.690314_114.048995-22.688018_114....,1699.3
1,0,2,motorway_link,114.049332-22.690314_114.049234-22.689926_114....,663.9
2,1,10107,motorway,114.048449-22.675017_114.048508-22.673645,152.0
3,2,8,motorway_link,114.04665-22.685071_114.046193-22.684735_114.0...,366.4
4,2,7,motorway_link,114.04665-22.685071_114.046416-22.684763_114.0...,1202.3

In [94]:
# Directed edges in the road network
road_edges = edges[
    ["Origin", "Destination"]
].drop_duplicates()

# Connect incoming and outgoing edges at each intersection
turn_options = road_edges.merge(
    road_edges,
    left_on="Destination",
    right_on="Origin",
    suffixes=("_in", "_out"),
)

turn_options = turn_options[
    ["Origin_in", "Destination_in", "Destination_out"]
].rename(
    columns={
        "Origin_in": "incoming",
        "Destination_in": "intersection",
        "Destination_out": "outgoing",
    }
).drop_duplicates()

print(f"Possible turning combinations: {len(turn_options):,}")
display(turn_options.head())

Possible turning combinations: 72,495

   incoming  intersection  outgoing
0         0             1     10107
1         0             2         8
2         0             2         7
3         1         10107      3903
4         2             8     11780

72k topologically possible turning combinations

In [95]:
# calculating smoothed baseline probabilities
alpha = 1.0

smoothed_baseline = turn_options.merge(
    baseline_counts[
        ["incoming", "intersection", "outgoing", "count"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="one_to_one",
)

# Unobserved turns have a training count of zero
smoothed_baseline["count"] = (
    smoothed_baseline["count"].fillna(0)
)

# Number of possible outgoing roads per incoming-road/intersection pair
smoothed_baseline["K"] = (
    smoothed_baseline
    .groupby(["incoming", "intersection"])["outgoing"]
    .transform("size")
)

# Total training observations for each approach
smoothed_baseline["total"] = (
    smoothed_baseline
    .groupby(["incoming", "intersection"])["count"]
    .transform("sum")
)

smoothed_baseline["probability"] = (
    (smoothed_baseline["count"] + alpha)
    / (smoothed_baseline["total"] + alpha * smoothed_baseline["K"])
)

print("Smoothed turning combinations:", len(smoothed_baseline))

# Check that probabilities sum to 1 for every approach
probability_sums = (
    smoothed_baseline
    .groupby(["incoming", "intersection"])["probability"]
    .sum()
)

print(
    "All probability distributions sum to 1:",
    (probability_sums - 1).abs().max() < 1e-10
)

display(smoothed_baseline.head(10))

Smoothed turning combinations: 72495
All probability distributions sum to 1: True

   incoming  intersection  outgoing  count  K  total  probability
0         0             1     10107    0.0  1    0.0          1.0
1         0             2         8    0.0  2    0.0          0.5
2         0             2         7    0.0  2    0.0          0.5
3         1         10107      3903    0.0  1    0.0          1.0
4         2             8     11780    0.0  1    0.0          1.0
5         2             7      1206    0.0  1    0.0          1.0
6         3             4         6    0.0  2    0.0          0.5
7         3             4         7    0.0  2    0.0          0.5
8         3             5     11895    0.0  1    0.0          1.0
9         4             6         8    0.0  1    0.0          1.0

Evaluation of validation through logloss

In [96]:
import numpy as np

validation_scored = validation_movements.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing", "probability"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
)

print("Validation movements:", len(validation_scored))
print(
    "Missing predictions:",
    validation_scored["probability"].isna().sum()
)

if validation_scored["probability"].isna().any():
    print("Cannot evaluate until missing predictions are resolved.")
else:
    validation_log_loss = -np.log(
        validation_scored["probability"]
    ).mean()

    print(f"Validation log loss: {validation_log_loss:.6f}")

Validation movements: 2095554
Missing predictions: 0
Validation log loss: 0.312909

In [ ]:
# evaluating branching points separately

# num of possible outgoing roads at each approach
approach_options = (
    smoothed_baseline[
        ["incoming", "intersection", "K"]
    ]
    .drop_duplicates()
)

validation_scored = validation_scored.merge(
    approach_options,
    on=["incoming", "intersection"],
    how="left",
    validate="many_to_one",
)

# evaluate only approaches with multiple possible outgoing roads
branching_validation = validation_scored.loc[
    validation_scored["K"] > 1
]

branching_log_loss = -np.log(
    branching_validation["probability"]
).mean()

print(f"Branching movements: {len(branching_validation):,}")
print(
    f"Share of validation movements: "
    f"{len(branching_validation) / len(validation_scored):.2%}"
)
print(f"Overall log loss: {validation_log_loss:.6f}")
print(f"Branching log loss: {branching_log_loss:.6f}")

Branching movements: 1,725,586
Share of validation movements: 82.35%
Overall log loss: 0.312909
Branching log loss: 0.379998

### Building time-dependent baseline

P(outgoing|intersection,hour)

In [99]:
# Count movements by approach, outgoing road, and hour
hourly_train_counts = (
    train_movements
    .groupby(["incoming", "intersection", "outgoing", "hour"])
    .size()
    .rename("count")
    .reset_index()
)

# Create possible turning options for every modeled hour
hourly_options = turn_options.merge(
    pd.DataFrame({"hour": range(9, 19)}),
    how="cross",
)

# Include turns that were never observed during training
hourly_baseline = hourly_options.merge(
    hourly_train_counts,
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="one_to_one",
)

hourly_baseline["count"] = hourly_baseline["count"].fillna(0)

hourly_baseline["K"] = (
    hourly_baseline
    .groupby(["incoming", "intersection", "hour"])["outgoing"]
    .transform("size")
)

hourly_baseline["total"] = (
    hourly_baseline
    .groupby(["incoming", "intersection", "hour"])["count"]
    .transform("sum")
)

hourly_baseline["probability"] = (
    (hourly_baseline["count"] + alpha)
    / (hourly_baseline["total"] + alpha * hourly_baseline["K"])
)

print("Hourly turning combinations:", len(hourly_baseline))

probability_sums = (
    hourly_baseline
    .groupby(["incoming", "intersection", "hour"])["probability"]
    .sum()
)

print(
    "All probabilities sum to 1:",
    (probability_sums - 1).abs().max() < 1e-10
)

display(hourly_baseline.head())

Hourly turning combinations: 724950
All probabilities sum to 1: True

   incoming  intersection  outgoing  hour  count  K  total  probability
0         0             1     10107     9    0.0  1    0.0          1.0
1         0             1     10107    10    0.0  1    0.0          1.0
2         0             1     10107    11    0.0  1    0.0          1.0
3         0             1     10107    12    0.0  1    0.0          1.0
4         0             1     10107    13    0.0  1    0.0          1.0

In [100]:
hourly_validation = validation_movements.merge(
    hourly_baseline[
        ["incoming", "intersection", "outgoing", "hour", "probability"]
    ],
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="many_to_one",
)

missing = hourly_validation["probability"].isna().sum()

print(f"Missing predictions: {missing:,}")

if missing == 0:
    hourly_log_loss = -np.log(
        hourly_validation["probability"]
    ).mean()

    # Evaluate on the same branching movements as the static baseline
    hourly_branching = hourly_validation.merge(
        approach_options,
        on=["incoming", "intersection"],
        how="left",
        validate="many_to_one",
    )

    hourly_branching = hourly_branching.loc[
        hourly_branching["K"] > 1
    ]

    hourly_branching_log_loss = -np.log(
        hourly_branching["probability"]
    ).mean()

    print("\nValidation log loss (lower is better)")
    print(f"Static baseline, all:       {validation_log_loss:.6f}")
    print(f"Hourly baseline, all:       {hourly_log_loss:.6f}")
    print(f"Static baseline, branching: {branching_log_loss:.6f}")
    print(f"Hourly baseline, branching: {hourly_branching_log_loss:.6f}")

Missing predictions: 0

Validation log loss (lower is better)
Static baseline, all:       0.312909
Hourly baseline, all:       0.311626
Static baseline, branching: 0.379998
Hourly baseline, branching: 0.378439

The improvement is small but positive, Turning decisions depend on time, but the hour alone adds close to none predictive information.

Brier score calcultion

In [101]:
# Sum of squared probabilities for each approach
static_squared = (
    smoothed_baseline
    .assign(p_squared=lambda df: df["probability"] ** 2)
    .groupby(["incoming", "intersection"])["p_squared"]
    .sum()
    .rename("sum_p_squared")
    .reset_index()
)

static_brier_df = validation_scored.merge(
    static_squared,
    on=["incoming", "intersection"],
    how="left",
    validate="many_to_one",
)

static_brier_df["brier"] = (
    1
    - 2 * static_brier_df["probability"]
    + static_brier_df["sum_p_squared"]
)

print(f"Static Brier, all: {static_brier_df['brier'].mean():.6f}")
print(
    "Static Brier, branching:",
    f"{static_brier_df.loc[static_brier_df['K'] > 1, 'brier'].mean():.6f}"
)

Static Brier, all: 0.182548
Static Brier, branching: 0.221686

In [102]:
# Sum of squared probabilities for each approach and hour
hourly_squared = (
    hourly_baseline
    .assign(p_squared=lambda df: df["probability"] ** 2)
    .groupby(["incoming", "intersection", "hour"])["p_squared"]
    .sum()
    .rename("sum_p_squared")
    .reset_index()
)

hourly_brier_df = hourly_branching.merge(
    hourly_squared,
    on=["incoming", "intersection", "hour"],
    how="left",
    validate="many_to_one",
)

hourly_brier_df["brier"] = (
    1
    - 2 * hourly_brier_df["probability"]
    + hourly_brier_df["sum_p_squared"]
)

print("Brier score comparison (branching points)")
print(f"Static baseline: {static_brier_df.loc[static_brier_df['K'] > 1, 'brier'].mean():.6f}")
print(f"Hourly baseline: {hourly_brier_df['brier'].mean():.6f}")

Brier score comparison (branching points)
Static baseline: 0.221686
Hourly baseline: 0.220082

Again, the hourly metric performs slighly better

# Modeling
## Data preparation for ML model

let's try out a binary candidate-choice model CatBoost

features:
- incoming - incoming road's origin node
- intersection - current intersection
- hour - hour of day
- outgoing - candidate outgoing road

for each possible outgoing road, predict how likely the vehicle is to choose it, then normalize the candidate scores into a probability distribution

In [103]:
from catboost import CatBoostClassifier

print("CatBoost imported successfully")

CatBoost imported successfully

In [104]:
# sample from training data only
ml_sample = train_movements.sample(
    n=10_000,
    random_state=42,
)

# adding all possible outgoing roads for each observed approach
ml_candidates = ml_sample[
    ["incoming", "intersection", "outgoing", "hour"]
].rename(
    columns={"outgoing": "actual_outgoing"}
).merge(
    turn_options,
    on=["incoming", "intersection"],
    how="inner",
    validate="many_to_many",
)

# labeling the road actually taken
ml_candidates["chosen"] = (
    ml_candidates["outgoing"]
    == ml_candidates["actual_outgoing"]
).astype("int8")

print("Original movements:", len(ml_sample))
print("Candidate rows:", len(ml_candidates))
print("Positive labels:", ml_candidates["chosen"].sum())

display(ml_candidates.head(10))

Original movements: 10000
Candidate rows: 26362
Positive labels: 10000

   incoming  intersection  actual_outgoing  hour  outgoing  chosen
0      9602          6783             6782    17      6786       0
1      9602          6783             6782    17      6779       0
2      9602          6783             6782    17      6782       1
3      6889          3938            11346     9      3937       0
4      6889          3938            11346     9     11346       1
5      6889          3938            11346     9      6889       0
6      6889          3938            11346     9      6907       0
7     10224          4170             4183    17     10049       0
8     10224          4170             4183    17      3928       0
9     10224          4170             4183    17      4183       1

In [105]:
# training model

from catboost import CatBoostClassifier

features = ["incoming", "intersection", "outgoing", "hour"]
categorical_features = ["incoming", "intersection", "outgoing"]

X_train_ml = ml_candidates[features].copy()

for col in categorical_features:
    X_train_ml[col] = X_train_ml[col].astype(str)

y_train_ml = ml_candidates["chosen"]

ml_model = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.05,
    loss_function="Logloss",
    random_seed=42,
    verbose=50,
    thread_count=4,
)

ml_model.fit(
    X_train_ml,
    y_train_ml,
    cat_features=categorical_features,
)

0:	learn: 0.6533733	total: 201ms	remaining: 40s
50:	learn: 0.3287386	total: 3.55s	remaining: 10.4s
100:	learn: 0.3141187	total: 6.47s	remaining: 6.34s
150:	learn: 0.3064600	total: 9.29s	remaining: 3.01s
199:	learn: 0.2994007	total: 12s	remaining: 0us

CatBoostClassifier(depth=6, iterations=200, learning_rate=0.05, loss_function='Logloss', random_seed=42, thread_count=4, verbose=50)

In [108]:
# evaluating the model

val_sample = validation_movements.sample(
    n=10_000,
    random_state=42,
).reset_index(drop=True)

# assigning a unique ID to each movement
val_sample["movement_id"] = val_sample.index

val_candidates = val_sample[
    ["movement_id", "incoming", "intersection", "outgoing", "hour"]
].rename(
    columns={"outgoing": "actual_outgoing"}
).merge(
    turn_options,
    on=["incoming", "intersection"],
    how="inner",
)

# preparing model features
X_val_ml = val_candidates[features].copy()

for col in categorical_features:
    X_val_ml[col] = X_val_ml[col].astype(str)

# predicting a score for each possible outgoing road
val_candidates["score"] = ml_model.predict_proba(X_val_ml)[:, 1]

# normalize within each movement's candidate set
val_candidates["probability"] = (
    val_candidates["score"]
    / val_candidates.groupby("movement_id")["score"].transform("sum")
)

# candidate distributions
probability_sums = val_candidates.groupby("movement_id")["probability"].sum()

print("Validation movements:", len(val_sample))
print("Candidate rows:", len(val_candidates))
print(
    "All probabilities sum to 1:",
    np.allclose(probability_sums, 1)
)

# getting probability assigned to the actual outgoing road
actual_predictions = val_candidates.loc[
    val_candidates["outgoing"] == val_candidates["actual_outgoing"]
]

ml_validation_log_loss = -np.log(
    actual_predictions["probability"].clip(lower=1e-15)
).mean()

print(f"CatBoost validation log loss: {ml_validation_log_loss:.6f}")

Validation movements: 10000
Candidate rows: 26170
All probabilities sum to 1: True
CatBoost validation log loss: 0.404642

In [109]:
comparison = val_sample.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing", "probability"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
).rename(columns={"probability": "static_probability"})

comparison = comparison.merge(
    hourly_baseline[
        ["incoming", "intersection", "outgoing", "hour", "probability"]
    ],
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="many_to_one",
).rename(columns={"probability": "hourly_probability"})

print("Missing baseline predictions:")
print(comparison[
    ["static_probability", "hourly_probability"]
].isna().sum())

print("\nLog loss on the same 10,000 validation movements:")
print(f"Static baseline: {(-np.log(comparison['static_probability'])).mean():.6f}")
print(f"Hourly baseline: {(-np.log(comparison['hourly_probability'])).mean():.6f}")
print(f"CatBoost:        {ml_validation_log_loss:.6f}")

Missing baseline predictions:
static_probability    0
hourly_probability    0
dtype: int64

Log loss on the same 10,000 validation movements:
Static baseline: 0.322594
Hourly baseline: 0.321597
CatBoost:        0.404642

frequency baselines learned from roughly 10 million movements, while CatBoost only saw 10,000 + CatBoost currently learns whether each candidate road is chosen independently, rather than directly optimizing the probability distribution across all outgoing choices.

In [111]:
# larger training sample
ml_sample_100k = train_movements.sample(
    n=100_000,
    random_state=42,
).reset_index(drop=True)

ml_candidates_100k = (
    ml_sample_100k[
        ["incoming", "intersection", "outgoing", "hour"]
    ]
    .rename(columns={"outgoing": "actual_outgoing"})
    .merge(
        turn_options,
        on=["incoming", "intersection"],
        how="inner",
        validate="many_to_many",
    )
)

ml_candidates_100k["chosen"] = (
    ml_candidates_100k["outgoing"]
    == ml_candidates_100k["actual_outgoing"]
).astype("int8")

print(f"Training movements: {len(ml_sample_100k):,}")
print(f"Candidate rows: {len(ml_candidates_100k):,}")
print(f"Positive labels: {ml_candidates_100k['chosen'].sum():,}")

Training movements: 100,000
Candidate rows: 263,362
Positive labels: 100,000

In [112]:
X_train_100k = ml_candidates_100k[features].copy()

for col in categorical_features:
    X_train_100k[col] = X_train_100k[col].astype(str)

y_train_100k = ml_candidates_100k["chosen"]

ml_model_100k = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.05,
    loss_function="Logloss",
    random_seed=42,
    verbose=50,
    thread_count=4,
)

ml_model_100k.fit(
    X_train_100k,
    y_train_100k,
    cat_features=categorical_features,
)

0:	learn: 0.6312231	total: 229ms	remaining: 45.6s
50:	learn: 0.2542610	total: 6.84s	remaining: 20s
100:	learn: 0.2475596	total: 13.4s	remaining: 13.2s
150:	learn: 0.2458348	total: 20s	remaining: 6.49s
199:	learn: 0.2448868	total: 26.2s	remaining: 0us

CatBoostClassifier(depth=6, iterations=200, learning_rate=0.05, loss_function='Logloss', random_seed=42, thread_count=4, verbose=50)

In [114]:
# evaluate 100k model
# Predict with the larger CatBoost model
scores_100k = ml_model_100k.predict_proba(X_val_ml)[:, 1]

# Normalize candidate scores within each movement
val_candidates["probability_100k"] = (
    scores_100k
    / pd.Series(scores_100k, index=val_candidates.index)
      .groupby(val_candidates["movement_id"])
      .transform("sum")
)

# Extract probabilities assigned to the actual chosen roads
actual_100k = val_candidates.loc[
    val_candidates["outgoing"] == val_candidates["actual_outgoing"]
]

ml_log_loss_100k = -np.log(
    actual_100k["probability_100k"].clip(lower=1e-15)
).mean()

print("Validation log loss (same 10,000 movements):")
print(f"Static baseline:  {0.322594:.6f}")
print(f"Hourly baseline:  {0.321597:.6f}")
print(f"CatBoost 10k:     {ml_validation_log_loss:.6f}")
print(f"CatBoost 100k:    {ml_log_loss_100k:.6f}")

Validation log loss (same 10,000 movements):
Static baseline:  0.322594
Hourly baseline:  0.321597
CatBoost 10k:     0.404642
CatBoost 100k:    0.345419

Results improved significantly!! trying the model on 1m movements

In [115]:
ml_sample_1m = train_movements.sample(
    n=1_000_000,
    random_state=42,
)

ml_candidates_1m = (
    ml_sample_1m[
        ["incoming", "intersection", "outgoing", "hour"]
    ]
    .rename(columns={"outgoing": "actual_outgoing"})
    .merge(
        turn_options,
        on=["incoming", "intersection"],
        how="inner",
        validate="many_to_many",
    )
)

ml_candidates_1m["chosen"] = (
    ml_candidates_1m["outgoing"]
    == ml_candidates_1m["actual_outgoing"]
).astype("int8")

print(f"Candidate rows: {len(ml_candidates_1m):,}")
print(f"Positive labels: {ml_candidates_1m['chosen'].sum():,}")

Candidate rows: 2,630,225
Positive labels: 1,000,000

In [116]:
X_train_1m = ml_candidates_1m[features].copy()

for col in categorical_features:
    X_train_1m[col] = X_train_1m[col].astype(str)

y_train_1m = ml_candidates_1m["chosen"]

ml_model_1m = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.05,
    loss_function="Logloss",
    random_seed=42,
    verbose=50,
    thread_count=4,
)

ml_model_1m.fit(
    X_train_1m,
    y_train_1m,
    cat_features=categorical_features,
)

0:	learn: 0.6288337	total: 1.17s	remaining: 3m 53s
50:	learn: 0.2334425	total: 41.5s	remaining: 2m 1s
100:	learn: 0.2294920	total: 1m 22s	remaining: 1m 20s
150:	learn: 0.2287080	total: 2m 4s	remaining: 40.3s
199:	learn: 0.2283050	total: 2m 45s	remaining: 0us

CatBoostClassifier(depth=6, iterations=200, learning_rate=0.05, loss_function='Logloss', random_seed=42, thread_count=4, verbose=50)

In [117]:
# Predict candidate scores
scores_1m = ml_model_1m.predict_proba(X_val_ml)[:, 1]

# Normalize probabilities within each movement
val_candidates["probability_1m"] = (
    scores_1m
    / pd.Series(scores_1m, index=val_candidates.index)
      .groupby(val_candidates["movement_id"])
      .transform("sum")
)

# Select the probabilities of the actual outgoing roads
actual_1m = val_candidates.loc[
    val_candidates["outgoing"] == val_candidates["actual_outgoing"]
]

ml_log_loss_1m = -np.log(
    actual_1m["probability_1m"].clip(lower=1e-15)
).mean()

print("Validation log loss (same 10,000 movements):")
print(f"Static baseline:  {0.322594:.6f}")
print(f"Hourly baseline:  {0.321597:.6f}")
print(f"CatBoost 10k:     {ml_validation_log_loss:.6f}")
print(f"CatBoost 100k:    {ml_log_loss_100k:.6f}")
print(f"CatBoost 1M:      {ml_log_loss_1m:.6f}")

Validation log loss (same 10,000 movements):
Static baseline:  0.322594
Hourly baseline:  0.321597
CatBoost 10k:     0.404642
CatBoost 100k:    0.345419
CatBoost 1M:      0.336542

Model gradually improves. Let's inspect feature importance

In [118]:
importance = pd.DataFrame({
    "feature": features,
    "importance": ml_model_1m.get_feature_importance()
}).sort_values("importance", ascending=False)

print(importance.to_string(index=False))

     feature  importance
    outgoing   36.623561
    incoming   33.261301
intersection   30.060089
        hour    0.055048

CatBoost is relying almost entirely on road identities, with very little contribution from the hour of day. Let's actually test whether the hour feature helps

In [119]:
X_val_fixed_hour = X_val_ml.copy()
X_val_fixed_hour["hour"] = 12

scores_fixed_hour = ml_model_1m.predict_proba(
    X_val_fixed_hour
)[:, 1]

fixed_hour_probs = (
    pd.Series(scores_fixed_hour, index=val_candidates.index)
    / pd.Series(scores_fixed_hour, index=val_candidates.index)
      .groupby(val_candidates["movement_id"])
      .transform("sum")
)

actual_mask = (
    val_candidates["outgoing"]
    == val_candidates["actual_outgoing"]
)

fixed_hour_loss = -np.log(
    fixed_hour_probs.loc[actual_mask].clip(lower=1e-15)
).mean()

print(f"Original CatBoost:   {ml_log_loss_1m:.6f}")
print(f"Fixed-hour CatBoost: {fixed_hour_loss:.6f}")
print(f"Difference:          {fixed_hour_loss - ml_log_loss_1m:+.6f}")

Original CatBoost:   0.336542
Fixed-hour CatBoost: 0.336624
Difference:          +0.000082

Only a 0.024% increase in log loss, so, for this trained model, time of day has almost no influence. Now, let's examine mistakes

In [120]:
# Number of possible outgoing roads per movement
candidate_counts = (
    val_candidates.groupby("movement_id")
    .size()
    .rename("K")
)

# Probabilities assigned to the actual chosen roads
error_analysis = actual_1m[
    ["movement_id", "probability_1m"]
].merge(
    candidate_counts,
    on="movement_id"
)

error_analysis["log_loss"] = -np.log(
    error_analysis["probability_1m"].clip(lower=1e-15)
)

# Add baseline probabilities for the same movements
error_analysis = error_analysis.merge(
    comparison[["movement_id", "hourly_probability"]],
    on="movement_id"
)

error_analysis["baseline_log_loss"] = -np.log(
    error_analysis["hourly_probability"]
)

print(
    error_analysis.groupby("K").agg(
        movements=("movement_id", "count"),
        catboost_loss=("log_loss", "mean"),
        baseline_loss=("baseline_log_loss", "mean"),
    ).round(6)
)

   movements  catboost_loss  baseline_loss
K
1       1782       0.000000       0.000000
2       3229       0.185909       0.172343
3       2225       0.391123       0.375233
4       2576       0.689326       0.663422
5        177       0.649734       0.634109
6         11       0.378727       0.306570

Let"s try to give CatBoost access to the historical turning probabilities as feature

In [121]:
candidate_baseline = ml_candidates_1m.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing",
         "count", "probability"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
)

print("Missing baseline features:")
print(candidate_baseline[["count", "probability"]].isna().sum())

print("\nCandidate probability distribution:")
print(
    candidate_baseline["probability"]
    .describe()
)

print("\nShare of candidates with zero historical counts:")
print((candidate_baseline["count"] == 0).mean())

Missing baseline features:
count          0
probability    0
dtype: int64

Candidate probability distribution:
count    2.630225e+06
mean     3.801956e-01
std      4.073302e-01
min      3.209758e-05
25%      3.880719e-03
50%      1.661556e-01
75%      8.451891e-01
max      1.000000e+00
Name: probability, dtype: float64

Share of candidates with zero historical counts:
0.21890142478305089

Preparing leak-proof historical features

In [122]:
from sklearn.model_selection import train_test_split

unique_ml_trips = ml_sample_1m[
    ["VehicleID", "TripID"]
].drop_duplicates()

history_trips, hybrid_trips = train_test_split(
    unique_ml_trips,
    test_size=0.3,
    random_state=42,
)

history_movements = ml_sample_1m.merge(
    history_trips,
    on=["VehicleID", "TripID"],
    how="inner",
)

hybrid_movements = ml_sample_1m.merge(
    hybrid_trips,
    on=["VehicleID", "TripID"],
    how="inner",
)

print(f"History movements: {len(history_movements):,}")
print(f"Hybrid training movements: {len(hybrid_movements):,}")
print(
    "Total:",
    len(history_movements) + len(hybrid_movements)
)

History movements: 701,019
Hybrid training movements: 298,981
Total: 1000000

In [124]:
# calc hisotrical turn probabilities
# Count observed turns in the history subset
history_counts = (
    history_movements
    .groupby(["incoming", "intersection", "outgoing"])
    .size()
    .reset_index(name="count")
)

# Include all topologically possible turns
history_baseline = turn_options.merge(
    history_counts,
    on=["incoming", "intersection", "outgoing"],
    how="left",
)

history_baseline["count"] = (
    history_baseline["count"].fillna(0)
)

# Number of possible outgoing choices
history_baseline["K"] = (
    history_baseline
    .groupby(["incoming", "intersection"])["outgoing"]
    .transform("size")
)

# Total historical movements per incoming road/intersection
history_baseline["total"] = (
    history_baseline
    .groupby(["incoming", "intersection"])["count"]
    .transform("sum")
)

# Laplace-smoothed probabilities
history_baseline["probability"] = (
    (history_baseline["count"] + 1)
    / (history_baseline["total"] + history_baseline["K"])
)

# Verify valid probability distributions
probability_sums = (
    history_baseline
    .groupby(["incoming", "intersection"])["probability"]
    .sum()
)

print("Historical turn combinations:", len(history_baseline))
print("All probabilities sum to 1:", np.allclose(probability_sums, 1))
print("Observed turn combinations:", (history_baseline["count"] > 0).sum())

Historical turn combinations: 72495
All probabilities sum to 1: True
Observed turn combinations: 3475

In [125]:
hybrid_candidates = (
    hybrid_movements[
        ["incoming", "intersection", "outgoing", "hour"]
    ]
    .rename(columns={"outgoing": "actual_outgoing"})
    .merge(
        turn_options,
        on=["incoming", "intersection"],
        how="inner",
    )
)

hybrid_candidates["chosen"] = (
    hybrid_candidates["outgoing"]
    == hybrid_candidates["actual_outgoing"]
).astype("int8")

# Attach leakage-free historical features
hybrid_candidates = hybrid_candidates.merge(
    history_baseline[
        ["incoming", "intersection", "outgoing",
         "count", "total", "K", "probability"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
)

hybrid_candidates = hybrid_candidates.rename(
    columns={
        "count": "historical_count",
        "total": "historical_total",
        "probability": "historical_probability",
    }
)

print("Hybrid training movements:", len(hybrid_movements))
print("Candidate rows:", len(hybrid_candidates))
print("Positive labels:", hybrid_candidates["chosen"].sum())

print("\nMissing historical features:")
print(
    hybrid_candidates[
        ["historical_count", "historical_total",
         "K", "historical_probability"]
    ].isna().sum()
)

Hybrid training movements: 298981
Candidate rows: 785760
Positive labels: 298981

Missing historical features:
historical_count          0
historical_total          0
K                         0
historical_probability    0
dtype: int64

In [126]:
hybrid_features = [
    "incoming",
    "intersection",
    "outgoing",
    "hour",
    "historical_probability",
    "historical_count",
    "historical_total",
    "K",
]

X_hybrid_train = hybrid_candidates[hybrid_features].copy()

for col in categorical_features:
    X_hybrid_train[col] = X_hybrid_train[col].astype(str)

y_hybrid_train = hybrid_candidates["chosen"]

hybrid_model = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.05,
    loss_function="Logloss",
    random_seed=42,
    verbose=50,
    thread_count=4,
)

hybrid_model.fit(
    X_hybrid_train,
    y_hybrid_train,
    cat_features=categorical_features,
)

0:	learn: 0.6169861	total: 472ms	remaining: 1m 34s
50:	learn: 0.2239480	total: 22.5s	remaining: 1m 5s
100:	learn: 0.2217954	total: 42s	remaining: 41.2s
150:	learn: 0.2214254	total: 59.2s	remaining: 19.2s
199:	learn: 0.2211585	total: 1m 16s	remaining: 0us

CatBoostClassifier(depth=6, iterations=200, learning_rate=0.05, loss_function='Logloss', random_seed=42, thread_count=4, verbose=50)

In [128]:
hybrid_val = val_candidates.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing",
         "count", "total", "K", "probability"]
    ].rename(columns={
        "count": "historical_count",
        "total": "historical_total",
        "probability": "historical_probability",
    }),
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one",
)

X_hybrid_val = hybrid_val[hybrid_features].copy()

for col in categorical_features:
    X_hybrid_val[col] = X_hybrid_val[col].astype(str)

print("Missing historical features:")
print(X_hybrid_val.isna().sum())

Missing historical features:
incoming                  0
intersection              0
outgoing                  0
hour                      0
historical_probability    0
historical_count          0
historical_total          0
K                         0
dtype: int64

In [129]:
# Predict candidate scores
hybrid_val["score"] = hybrid_model.predict_proba(
    X_hybrid_val
)[:, 1]

# Normalize scores within each movement
hybrid_val["hybrid_probability"] = (
    hybrid_val["score"]
    / hybrid_val.groupby("movement_id")["score"].transform("sum")
)

# Select the actual outgoing road for each movement
hybrid_actual = hybrid_val.loc[
    hybrid_val["outgoing"] == hybrid_val["actual_outgoing"]
]

# Calculate validation log loss
hybrid_log_loss = -np.log(
    hybrid_actual["hybrid_probability"].clip(lower=1e-15)
).mean()

print("Validation log loss (same 10,000 movements):")
print(f"Static baseline:  {0.322594:.6f}")
print(f"Hourly baseline:  {0.321597:.6f}")
print(f"CatBoost 1M:      {ml_log_loss_1m:.6f}")
print(f"Hybrid CatBoost:  {hybrid_log_loss:.6f}")

Validation log loss (same 10,000 movements):
Static baseline:  0.322594
Hourly baseline:  0.321597
CatBoost 1M:      0.336542
Hybrid CatBoost:  0.324470

In [130]:
hybrid_importance = pd.DataFrame({
    "feature": hybrid_features,
    "importance": hybrid_model.get_feature_importance(),
}).sort_values("importance", ascending=False)

print(hybrid_importance.to_string(index=False))

               feature  importance
historical_probability   70.331432
      historical_count   17.044225
                     K    5.573265
      historical_total    2.660719
          intersection    2.223257
              outgoing    1.036055
              incoming    0.792403
                  hour    0.338644

In [131]:
# comparing individual prediction errors
hybrid_errors = hybrid_actual[
    ["movement_id", "hybrid_probability"]
].merge(
    comparison[
        ["movement_id", "static_probability"]
    ],
    on="movement_id",
    validate="one_to_one",
)

hybrid_errors["hybrid_loss"] = -np.log(
    hybrid_errors["hybrid_probability"].clip(lower=1e-15)
)

hybrid_errors["baseline_loss"] = -np.log(
    hybrid_errors["static_probability"].clip(lower=1e-15)
)

hybrid_errors["improvement"] = (
    hybrid_errors["baseline_loss"]
    - hybrid_errors["hybrid_loss"]
)

print("Movements where hybrid is better:",
      (hybrid_errors["improvement"] > 0).mean())

print("Movements where baseline is better:",
      (hybrid_errors["improvement"] < 0).mean())

print("Average improvement:",
      hybrid_errors["improvement"].mean())

print("\nImprovement distribution:")
print(hybrid_errors["improvement"].describe())

Movements where hybrid is better: 0.2079
Movements where baseline is better: 0.6139
Average improvement: -0.0018751162604389432

Improvement distribution:
count    10000.000000
mean        -0.001875
std          0.075454
min         -0.248629
25%         -0.026879
50%         -0.000154
75%          0.000000
max          0.942383
Name: improvement, dtype: float64

Trying to blend CatBoost's probabilities with the static baseline

In [132]:
blend_results = []

for w in [0.0, 0.1, 0.2, 0.3, 0.5, 0.75, 1.0]:
    blended_probability = (
        (1 - w) * hybrid_errors["static_probability"]
        + w * hybrid_errors["hybrid_probability"]
    )

    loss = -np.log(
        blended_probability.clip(lower=1e-15)
    ).mean()

    blend_results.append({
        "catboost_weight": w,
        "log_loss": loss,
    })

blend_results = pd.DataFrame(blend_results)

print(blend_results.to_string(index=False))

 catboost_weight  log_loss
            0.00  0.322594
            0.10  0.322502
            0.20  0.322485
            0.30  0.322536
            0.50  0.322825
            0.75  0.323496
            1.00  0.324470

In [133]:
hybrid_errors["static_probability"] = np.exp(
    -hybrid_errors["baseline_loss"]
)

In [135]:
# 20% CatBoost and 80% static baseline
hourly_blend = hybrid_errors.merge(
    comparison[["movement_id", "hourly_probability"]],
    on="movement_id",
    validate="one_to_one",
)

results = []

for w in [0.0, 0.1, 0.2, 0.3, 0.5, 0.75, 1.0]:
    p = (
        (1 - w) * hourly_blend["hourly_probability"]
        + w * hourly_blend["hybrid_probability"]
    )

    results.append({
        "catboost_weight": w,
        "log_loss": -np.log(p.clip(lower=1e-15)).mean(),
    })

hourly_blend_results = pd.DataFrame(results)

print(hourly_blend_results.to_string(index=False))

 catboost_weight  log_loss
            0.00  0.321597
            0.10  0.321275
            0.20  0.321126
            0.30  0.321127
            0.50  0.321519
            0.75  0.322658
            1.00  0.324470

In [137]:
# Brier score for the blended model
hybrid_val = hybrid_val.drop(
    columns=["hourly_probability"],
    errors="ignore"
)

hybrid_val = hybrid_val.merge(
    hourly_baseline[
        ["incoming", "intersection", "outgoing", "hour", "probability"]
    ].rename(columns={
        "probability": "hourly_probability"
    }),
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="many_to_one"
)

print("Missing hourly probabilities:",
      hybrid_val["hourly_probability"].isna().sum())

print("Rows:", len(hybrid_val))

Missing hourly probabilities: 0
Rows: 26170

In [138]:
# multiclass briar score
hybrid_val["blended_probability"] = (
    0.8 * hybrid_val["hourly_probability"]
    + 0.2 * hybrid_val["hybrid_probability"]
)

hybrid_val["actual"] = (
    hybrid_val["outgoing"] == hybrid_val["actual_outgoing"]
).astype(int)

brier_scores = {}

for model, column in {
    "Hourly baseline": "hourly_probability",
    "Hybrid CatBoost": "hybrid_probability",
    "80/20 blend": "blended_probability",
}.items():
    squared_errors = (
        hybrid_val[column] - hybrid_val["actual"]
    ) ** 2

    brier_scores[model] = (
        squared_errors.groupby(hybrid_val["movement_id"])
        .sum()
        .mean()
    )

for model, score in brier_scores.items():
    print(f"{model}: {score:.6f}")

Hourly baseline: 0.187853
Hybrid CatBoost: 0.189888
80/20 blend: 0.187748

In [139]:
# perfromance of whole validation set
print("Full validation movements:", len(validation_movements))
print("Current evaluation sample:", len(val_sample))

print(
    "Estimated candidate rows:",
    round(len(validation_movements) * len(val_candidates) / len(val_sample))
)

Full validation movements: 2095554
Current evaluation sample: 10000
Estimated candidate rows: 5484065

In [140]:
full_val = validation_movements[
    ["incoming", "intersection", "outgoing", "hour"]
].reset_index(drop=True).copy()

full_val["movement_id"] = full_val.index

batch_size = 50_000
n_batches = (len(full_val) + batch_size - 1) // batch_size

print("Validation movements:", len(full_val))
print("Batch size:", batch_size)
print("Number of batches:", n_batches)

print(full_val.head())

Validation movements: 2095554
Batch size: 50000
Number of batches: 42
   incoming  intersection  outgoing  hour  movement_id
0      9204          6851     11775    16            0
1      6851         11775      9737    16            1
2     11775          9737      9954    16            2
3      9737          9954      1535    16            3
4      9954          1535      6857    16            4

In [141]:
batch = full_val.iloc[:batch_size].copy()

batch_candidates = batch.rename(
    columns={"outgoing": "actual_outgoing"}
).merge(
    turn_options,
    on=["incoming", "intersection"],
    how="left",
    validate="many_to_many"
)

batch_candidates = batch_candidates.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing",
         "count", "total", "K", "probability"]
    ].rename(columns={
        "count": "historical_count",
        "total": "historical_total",
        "probability": "historical_probability",
    }),
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one"
)

batch_candidates = batch_candidates.merge(
    hourly_baseline[
        ["incoming", "intersection", "outgoing",
         "hour", "probability"]
    ].rename(columns={
        "probability": "hourly_probability"
    }),
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="many_to_one"
)

print("Movements:", batch["movement_id"].nunique())
print("Candidate rows:", len(batch_candidates))
print("Missing features:")
print(batch_candidates[
    ["historical_probability", "historical_count",
     "historical_total", "K", "hourly_probability"]
].isna().sum())

print("Unique movements after expansion:",
      batch_candidates["movement_id"].nunique())

Movements: 50000
Candidate rows: 132848
Missing features:
historical_probability    0
historical_count          0
historical_total          0
K                         0
hourly_probability        0
dtype: int64
Unique movements after expansion: 50000

In [142]:
# Prepare CatBoost features
X_batch = batch_candidates[hybrid_features].copy()

for col in categorical_features:
    X_batch[col] = X_batch[col].astype(str)

# Predict candidate scores
batch_candidates["score"] = hybrid_model.predict_proba(
    X_batch
)[:, 1]

# Normalize probabilities within each movement
batch_candidates["hybrid_probability"] = (
    batch_candidates["score"]
    / batch_candidates.groupby("movement_id")["score"].transform("sum")
)

# Blend hourly baseline (80%) and CatBoost (20%)
batch_candidates["blended_probability"] = (
    0.8 * batch_candidates["hourly_probability"]
    + 0.2 * batch_candidates["hybrid_probability"]
)

# Identify the actual outgoing road
batch_candidates["actual"] = (
    batch_candidates["outgoing"] == batch_candidates["actual_outgoing"]
).astype(int)

# Calculate metrics
for name, column in {
    "Hourly baseline": "hourly_probability",
    "80/20 blend": "blended_probability",
}.items():
    actual_probs = batch_candidates.loc[
        batch_candidates["actual"] == 1, column
    ]

    log_loss = -np.log(actual_probs.clip(lower=1e-15)).mean()

    brier = (
        (batch_candidates[column] - batch_candidates["actual"])
        .pow(2)
        .groupby(batch_candidates["movement_id"])
        .sum()
        .mean()
    )

    print(f"{name}: log loss = {log_loss:.6f}, Brier = {brier:.6f}")

Hourly baseline: log loss = 0.360635, Brier = 0.209215
80/20 blend: log loss = 0.359557, Brier = 0.208890

80/20 blend outperforms the hourly baseline on both metrics

In [143]:
#evaluating all 42 batches
totals = {
    "hourly": {"log_loss": 0.0, "brier": 0.0},
    "blend": {"log_loss": 0.0, "brier": 0.0},
}

for start in range(0, len(full_val), batch_size):
    batch = full_val.iloc[start:start + batch_size]

    candidates = batch.rename(
        columns={"outgoing": "actual_outgoing"}
    ).merge(
        turn_options,
        on=["incoming", "intersection"],
        how="left",
        validate="many_to_many"
    )

    candidates = candidates.merge(
        smoothed_baseline[
            ["incoming", "intersection", "outgoing",
             "count", "total", "K", "probability"]
        ].rename(columns={
            "count": "historical_count",
            "total": "historical_total",
            "probability": "historical_probability",
        }),
        on=["incoming", "intersection", "outgoing"],
        how="left",
        validate="many_to_one"
    )

    candidates = candidates.merge(
        hourly_baseline[
            ["incoming", "intersection", "outgoing",
             "hour", "probability"]
        ].rename(columns={
            "probability": "hourly_probability"
        }),
        on=["incoming", "intersection", "outgoing", "hour"],
        how="left",
        validate="many_to_one"
    )

    X = candidates[hybrid_features].copy()

    for col in categorical_features:
        X[col] = X[col].astype(str)

    candidates["score"] = hybrid_model.predict_proba(X)[:, 1]

    candidates["hybrid_probability"] = (
        candidates["score"]
        / candidates.groupby("movement_id")["score"].transform("sum")
    )

    candidates["blend_probability"] = (
        0.8 * candidates["hourly_probability"]
        + 0.2 * candidates["hybrid_probability"]
    )

    candidates["actual"] = (
        candidates["outgoing"] == candidates["actual_outgoing"]
    ).astype(int)

    assert candidates["actual"].sum() == len(batch)
    assert candidates[["hourly_probability", "blend_probability"]].notna().all().all()

    for name, column in {
        "hourly": "hourly_probability",
        "blend": "blend_probability",
    }.items():
        actual_probs = candidates.loc[candidates["actual"] == 1, column]

        totals[name]["log_loss"] += (
            -np.log(actual_probs.clip(lower=1e-15)).sum()
        )

        totals[name]["brier"] += (
            (candidates[column] - candidates["actual"])
            .pow(2)
            .sum()
        )

    print(
        f"Batch {start // batch_size + 1}/{n_batches} complete",
        end="\r"
    )

print("\nFull validation results:")

for name, metrics in totals.items():
    print(
        f"{name}: "
        f"log loss = {metrics['log_loss'] / len(full_val):.6f}, "
        f"Brier = {metrics['brier'] / len(full_val):.6f}"
    )

Batch 42/42 complete
Full validation results:
hourly: log loss = 0.311626, Brier = 0.181227
blend: log loss = 0.311424, Brier = 0.181219

In [144]:
totals = {
    "hourly": {"log_loss": 0.0, "brier": 0.0},
    "blend": {"log_loss": 0.0, "brier": 0.0},
}

for start in range(0, len(full_val), batch_size):
    batch = full_val.iloc[start:start + batch_size]

    candidates = batch.rename(
        columns={"outgoing": "actual_outgoing"}
    ).merge(
        turn_options,
        on=["incoming", "intersection"],
        how="left",
        validate="many_to_many"
    )

    candidates = candidates.merge(
        smoothed_baseline[
            ["incoming", "intersection", "outgoing",
             "count", "total", "K", "probability"]
        ].rename(columns={
            "count": "historical_count",
            "total": "historical_total",
            "probability": "historical_probability",
        }),
        on=["incoming", "intersection", "outgoing"],
        how="left",
        validate="many_to_one"
    )

    candidates = candidates.merge(
        hourly_baseline[
            ["incoming", "intersection", "outgoing",
             "hour", "probability"]
        ].rename(columns={
            "probability": "hourly_probability"
        }),
        on=["incoming", "intersection", "outgoing", "hour"],
        how="left",
        validate="many_to_one"
    )

    X = candidates[hybrid_features].copy()

    for col in categorical_features:
        X[col] = X[col].astype(str)

    candidates["score"] = hybrid_model.predict_proba(X)[:, 1]

    candidates["hybrid_probability"] = (
        candidates["score"]
        / candidates.groupby("movement_id")["score"].transform("sum")
    )

    candidates["blend_probability"] = (
        0.8 * candidates["hourly_probability"]
        + 0.2 * candidates["hybrid_probability"]
    )

    candidates["actual"] = (
        candidates["outgoing"] == candidates["actual_outgoing"]
    ).astype(int)

    assert candidates["actual"].sum() == len(batch)
    assert candidates[["hourly_probability", "blend_probability"]].notna().all().all()

    for name, column in {
        "hourly": "hourly_probability",
        "blend": "blend_probability",
    }.items():
        actual_probs = candidates.loc[candidates["actual"] == 1, column]

        totals[name]["log_loss"] += (
            -np.log(actual_probs.clip(lower=1e-15)).sum()
        )

        totals[name]["brier"] += (
            (candidates[column] - candidates["actual"])
            .pow(2)
            .sum()
        )

    print(
        f"Batch {start // batch_size + 1}/{n_batches} complete",
        end="\r"
    )

print("\nFull validation results:")

for name, metrics in totals.items():
    print(
        f"{name}: "
        f"log loss = {metrics['log_loss'] / len(full_val):.6f}, "
        f"Brier = {metrics['brier'] / len(full_val):.6f}"
    )

Batch 42/42 complete
Full validation results:
hourly: log loss = 0.311626, Brier = 0.181227
blend: log loss = 0.311424, Brier = 0.181219

In [145]:
branching_val = full_val.merge(
    smoothed_baseline[
        ["incoming", "intersection", "outgoing", "K"]
    ],
    on=["incoming", "intersection", "outgoing"],
    how="left",
    validate="many_to_one"
)

print("Total validation movements:", len(branching_val))
print("Branching movements (K > 1):", (branching_val["K"] > 1).sum())
print("Branching share:", (branching_val["K"] > 1).mean())
print("\nCandidate count distribution:")
print(branching_val["K"].value_counts().sort_index())

Total validation movements: 2095554
Branching movements (K > 1): 1725586
Branching share: 0.8234509824132425

Candidate count distribution:
K
1    369968
2    668129
3    475109
4    542481
5     38268
6      1599
Name: count, dtype: int64

In [146]:
branching_ids = set(
    branching_val.loc[
        branching_val["K"] > 1, "movement_id"
    ]
)

branching_hourly = validation_movements[
    ["incoming", "intersection", "outgoing", "hour"]
].reset_index(drop=True).copy()

branching_hourly["movement_id"] = branching_hourly.index

branching_hourly = branching_hourly[
    branching_hourly["movement_id"].isin(branching_ids)
].merge(
    hourly_baseline[
        ["incoming", "intersection", "outgoing", "hour", "probability"]
    ],
    on=["incoming", "intersection", "outgoing", "hour"],
    how="left",
    validate="many_to_one"
)

print("Branching movements:", len(branching_hourly))

branching_log_loss = -np.log(
    branching_hourly["probability"].clip(lower=1e-15)
).mean()

print(f"Hourly branching log loss: {branching_log_loss:.6f}")

Branching movements: 1725586
Hourly branching log loss: 0.378439

In [147]:
n_branching = (branching_val["K"] > 1).sum()

print("Full validation — branching movements (K > 1)\n")

for name, metrics in totals.items():
    branching_log_loss = metrics["log_loss"] / n_branching
    branching_brier = metrics["brier"] / n_branching

    print(
        f"{name}: "
        f"log loss = {branching_log_loss:.6f}, "
        f"Brier = {branching_brier:.6f}"
    )

Full validation — branching movements (K > 1)

hourly: log loss = 0.378439, Brier = 0.220082
blend: log loss = 0.378194, Brier = 0.220072